name: Antivitsit
favicon: null
layout_spectrum: 0.9652
typography_spectrum: 0.92401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#dfdfdf'
    - '#666661'
    - '#de594a'
    - '#53a258'
  brandStrength: 0.1875
  lightness: 0.9628557809628546
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
