name: Antivitsit
favicon: null
layout_spectrum: 0.3954777920152992
typography_spectrum: 0.88984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#dfdfdf'
    - '#666661'
    - '#de594a'
    - '#53a258'
  brandStrength: 0.6875
  lightness: 0.9628557809628546
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
